name: test
on:
  push: null
jobs:
  get-go-version:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.get-go-version.outputs.go-version }}
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
    - name: Determine Go version
      id: get-go-version
      run: 'echo "Building with Go $(cat .go-version)"

        echo "go-version=$(cat .go-version)" >> $GITHUB_OUTPUT

        '
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
    - name: Set up Go
      uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
      with:
        go-version: ${{ steps.get-go-version.outputs.go-version }}
    - name: Test
      run: go test -v ./...
